apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    run: kubernetes-demo
spec:
  initContainers:
    - name: init-download
      image: busybox
      command:
        [
          "sh",
          "-c",
          "wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/ing-analytics/dock-and-deploy-workshop/refs/heads/main/assets/demo_static_site.html",
        ]
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      emptyDir: {}
