apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-deploy
  name: sample-deploy
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-deploy
  type: ClusterIP
status:
  loadBalancer: {}
