apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    run: exercise-1
spec:
  replicas: 2 # Two pods
  selector:
    matchLabels:
      run: exercise-1
  template:
    metadata:
      labels:
        run: exercise-1
    spec:
      initContainers:
        - name: init-download
          image: busybox
          command:
            [
              "sh",
              "-c",
              "wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/ing-analytics/dock-and-deploy-workshop/refs/heads/kubernetes-practice/assets/ex_static_site.html",
            ]
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          emptyDir: {}
