apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    run: exercise-1
spec:
  initContainers:
    - name: init-download-page
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      # TODO: Add init container definition:
  containers:
    - name: nginx-container
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      # TODO: Define the container:
