version: '3.8'

services:
  web:
    build: ./web
    container_name: web_app
    volumes:
      - ./web:/usr/src/web
    networks:
      - app_network
    ports:
      - "5000:5000"
    working_dir: /usr/src/web
    command: python web.py

  db:
    image: postgres:13
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

networks:
  app_network:
    driver: bridge

volumes:
  db_data: