apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      initContainers:
        - name: init-download
          image: busybox
          command:
            [
              "sh",
              "-c",
              "wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/ing-analytics/dock-and-deploy-workshop/refs/heads/kubernetes-practice-2/assets/ex_data_site.html",
            ]
          volumeMounts:
            - name: site-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: site-container
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: site-volume
            mountPath: /usr/share/nginx/html
          - name: data-volume
            mountPath: /usr/share/nginx/html/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
          configMap:
            name: data-config
        - name: site-volume
          emptyDir: {}
