apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  data.csv: |
    transaction_id,amount_eur,timestamp
    1,67.13,2025-04-16T04:12:41Z
    2,13.94,2025-04-16T01:40:10Z
    3,26.78,2025-04-16T05:25:28Z
    4,50.02,2025-04-16T22:08:59Z
    5,82.60,2025-04-16T06:05:49Z
    6,15.42,2025-04-16T09:25:03Z
    7,93.42,2025-04-16T12:13:28Z
    8,21.45,2025-04-16T18:55:28Z
    9,69.98,2025-04-16T19:39:16Z
    10,45.82,2025-04-16T22:26:21Z
  timestamp.txt: |
    2025-04-09T00:00:00
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      initContainers:
        - name: init-download
          image: busybox
          command:
            [
              "sh",
              "-c",
              "wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/ing-analytics/dock-and-deploy-workshop/refs/heads/kubernetes-practice-2/assets/ex_data_site.html",
            ]
          volumeMounts:
            - name: site-volume
              mountPath: /usr/share/nginx/html
      containers:
        - name: site-container
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: site-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: site-volume
          configMap:
            name: site-config
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  selector:
    app: site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
